config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  resources :articles, only: [:show, :index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# The helps us communicate with the data base. So we can collect all instances of Article from the database. Without specifying this class it's impossible to collect articles from th database.
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    # to make the variable available to the view, we have to make it an instance variable
    @article = Article.find(params[:id])
    # The id is being passed to the application using a params hash
  end

  def index 
    @articles = Article.all
  end

  def new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    # render plain: params[:article], status: :unprocessable_entity
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1>Showing all articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%  @articles.each do |article|%>
    <tr>
      <td><%= article.title%></td>
      <td><%= article.description%></td>
      <td>Some Place Holder</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= form_with scope: :article, url: articles_path, local: true do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description%><br />
     <%= f.text_area :description%>
  </p>
  <p>
    <%= f.submit%>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1>Showing Article Details</h1>

<p>Title: <strong><%=@article.title%></strong></p>
<p>Description: <strong><%=@article.description%></strong></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alphablog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>